create adding tasks
lamngockhuong/laravel_quickstart pull request #4
Opened 2017-12-04 08:19 UTC by lamngockhuong

2017-12-04 08:19 UTC, lamngockhuong commented
ready

2017-12-04 09:00 UTC, trangkarol commented on resources/views/common/errors.blade.php
> +        <strong>Whoops! Something went wrong! I hate you!</strong>
I18n: Em nghiên cứu ở chỗ này nhé https://laravel.com/docs/5.5/localization

2017-12-04 09:00 UTC, trangkarol commented on resources/views/common/success.blade.php
> +        <strong>Successfully! I Love you so much!</strong>
I18n

2017-12-04 09:00 UTC, trangkarol commented on resources/views/layouts/app.blade.php
> +    <title>Laravel Quickstart - Basic</title>
I18n

2017-12-04 09:00 UTC, trangkarol commented on resources/views/tasks.blade.php
> +                    New Task
I18n

2017-12-04 09:00 UTC, trangkarol commented on app/Http/Controllers/TaskController.php
> +        ]);
Nghiên cứu https://laravel.com/docs/5.5/validation#form-request-validation để clean code chỗ này em nhé

2017-12-04 09:00 UTC, trangkarol commented on app/Http/Controllers/TaskController.php
> +        $message = "\"{$task->name}\" was added successfully";
I18n

2017-12-04 09:00 UTC, trangkarol commented on app/Http/Controllers/TaskController.php
> +        return redirect('/')->with('message', $message);
Convention: Trước return nếu là 1 đoạn code logic thì có 1 dòng trắng

2017-12-04 09:00 UTC, trangkarol commented on resources/views/layouts/app.blade.php
> +                Task List
I18n

2017-12-04 09:00 UTC, trangkarol commented on routes/web.php
> +Route::post('/task', 'TaskController@create');
Em nghiên cứu route resource để làm chỗ này nhé

2017-12-04 09:00 UTC, trangkarol commented
commented

2017-12-05 05:46 UTC, lamngockhuong commented on app/Http/Controllers/TaskController.php
> +        ]);
Đã fix chị nhá

2017-12-05 05:47 UTC, lamngockhuong commented on app/Http/Controllers/TaskController.php
> +        return redirect('/')->with('message', $message);
Đã fix ạ

2017-12-05 06:20 UTC, lamngockhuong commented on routes/web.php
> +Route::post('/task', 'TaskController@create');
Dạ em đã fix 💃

2017-12-05 07:10 UTC, lamngockhuong commented on resources/views/common/success.blade.php
> +        <strong>Successfully! I Love you so much!</strong>
fixed 💃

2017-12-05 07:10 UTC, lamngockhuong commented on resources/views/layouts/app.blade.php
> +    <title>Laravel Quickstart - Basic</title>
fixed 💃

2017-12-05 07:10 UTC, lamngockhuong commented on resources/views/layouts/app.blade.php
> +                Task List
fixed 💃

2017-12-05 07:10 UTC, lamngockhuong commented on resources/views/tasks.blade.php
> +                    New Task
fixed 💃

2017-12-05 07:10 UTC, lamngockhuong commented on resources/views/common/errors.blade.php
> +        <strong>Whoops! Something went wrong! I hate you!</strong>
fixed 💃

2017-12-05 07:10 UTC, lamngockhuong commented on app/Http/Controllers/TaskController.php
> +        $message = "\"{$task->name}\" was added successfully";
fixed 💃

2017-12-05 07:10 UTC, lamngockhuong commented
ready

2017-12-05 07:28 UTC, huynhquangdiep requested changes
commented

2017-12-05 07:28 UTC, at-diephq commented on app/Http/Controllers/TaskController.php
> +    public function index() {
dấu `{` mở function cho xuống dòng luôn em

2017-12-05 07:28 UTC, at-diephq commented on resources/lang/vi/validation.php
> +<?php
file này validate tiếng Việt sao nội dung toàn tiếng Anh thế em :-?

2017-12-05 07:28 UTC, at-diephq commented on resources/views/common/errors.blade.php
> +@endif
Thiếu dòng trắng cuối file

2017-12-05 07:28 UTC, at-diephq commented on resources/views/layouts/app.blade.php
> +    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
không nên dùng cdn này em, mặc dù nhẹ hơn cho project như mạng có vấn đề thì k load được, hoặc đang code mà k có mạng thì cũng k chạy được.

2017-12-05 07:28 UTC, at-diephq commented on resources/views/layouts/app.blade.php
> +    </style>
CSS thì định nghĩa một file khác để code nhé

2017-12-05 07:28 UTC, at-diephq commented on resources/views/layouts/app.blade.php
> +            <a class="navbar-brand" href="{{ url('/') }}">
Không nên dùng url, vì sau này url thay đổi thì sẽ rất mất công để tìm và sửa, thay vào đó em có thể dùng route name nhé :D

2017-12-05 07:28 UTC, at-diephq commented on resources/views/layouts/app.blade.php
> +{{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
không khuyến khích code đã comment, k dùng thì xóa luôn

2017-12-05 07:28 UTC, at-diephq commented on resources/views/tasks.blade.php
> +                    <form action="{{ url('task') }}" method="POST" class="form-horizontal">
Sửa dụng form laravel em nhé 
> https://laravelcollective.com/docs/master/html

2017-12-05 07:28 UTC, at-diephq commented on routes/web.php
> +use Illuminate\Support\Facades\Route;
> mục đích là gì ?

2017-12-05 07:28 UTC, trangkarol commented on app/Http/Controllers/TaskController.php
> +            $message = __('task.message.crsuccessnoty', ['Name' => "{$task->name}"]);
Em nên dùng trans thay cho `__` e hì. Nhìn nó tường minh hơn

2017-12-05 07:28 UTC, trangkarol commented on app/Http/Requests/TaskRequest.php
> +                    'name' => 'required|max:100'
Covention: Phần tử cuối cùng của array phải có dấu `,`

2017-12-05 07:28 UTC, trangkarol commented on resources/lang/en/task.php
> +        'button' => 'Add Task',
Covention: Phần tử cuối cùng của array phải có dấu `,`

2017-12-05 07:28 UTC, trangkarol commented on resources/views/common/errors.blade.php
> +@endif
Covention: thiếu end line

2017-12-05 07:28 UTC, at-diephq commented
commented
Em xem và fix những chổ tương tự nhé

2017-12-05 07:28 UTC, trangkarol commented
commented

2017-12-05 08:15 UTC, lamngockhuong commented on resources/lang/vi/validation.php
> +<?php
Em chẳng biết cái Task đó dịch ra tiếng Việt là gì nên .... 💃

2017-12-05 08:15 UTC, lamngockhuong commented on resources/views/common/errors.blade.php
> +@endif
Đã fix ạ

2017-12-05 08:15 UTC, lamngockhuong commented on resources/views/common/errors.blade.php
> +@endif
Dạ 🗡

2017-12-05 08:15 UTC, lamngockhuong commented on resources/views/layouts/app.blade.php
> +    </style>
Em đã chuyển vào file style.css

2017-12-05 08:15 UTC, lamngockhuong commented on routes/web.php
> +use Illuminate\Support\Facades\Route;
Để mới có thể sử dụng được các phương thức của Route a 👯‍♂️

2017-12-05 08:15 UTC, lamngockhuong commented on resources/views/layouts/app.blade.php
> +{{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
Đã xóa rồi a 🗡

2017-12-05 08:15 UTC, lamngockhuong commented on app/Http/Controllers/TaskController.php
> +    public function index() {
Dạ em đã fix

2017-12-05 08:15 UTC, lamngockhuong commented on app/Http/Controllers/TaskController.php
> +            $message = __('task.message.crsuccessnoty', ['Name' => "{$task->name}"]);
Đã fix

2017-12-05 08:15 UTC, lamngockhuong commented on resources/lang/en/task.php
> +        'button' => 'Add Task',
Đã fix

2017-12-05 08:15 UTC, lamngockhuong commented on resources/views/layouts/app.blade.php
> +    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
Em đã fix rồi a nhá

2017-12-05 08:15 UTC, lamngockhuong commented on resources/views/layouts/app.blade.php
> +            <a class="navbar-brand" href="{{ url('/') }}">
Dạ em đã fix

2017-12-05 08:51 UTC, lamngockhuong commented on resources/views/tasks.blade.php
> +                    <form action="{{ url('task') }}" method="POST" class="form-horizontal">
Em đã fix a nhé

2017-12-05 08:51 UTC, lamngockhuong commented
ready

2017-12-05 08:53 UTC, trangkarol commented
commented
e có quên push code lên không rứa Khương

2017-12-05 09:01 UTC, lamngockhuong commented
ready

2017-12-05 09:19 UTC, at-diephq commented on routes/web.php
> +use Illuminate\Support\Facades\Route;
@lamngockhuong không cần thiết đâu em

2017-12-05 09:23 UTC, at-diephq commented
commented 
Sử dụng webpack để quản lý các các package của mình nhé, đưa hết lên git làm gì cho nặng

2017-12-05 09:27 UTC, lamngockhuong commented on routes/web.php
> +use Illuminate\Support\Facades\Route;
Dạ. em xóa rồi

2017-12-08 01:37 UTC, lamngockhuong commented
ready

2017-12-08 01:43 UTC, at-diephq commented on public/css/style.css
> +}
convention

2017-12-08 01:43 UTC, at-diephq commented on public/js/npm.js
> +require('../../js/affix.js')
dòng trắng cuối file

2017-12-08 01:43 UTC, at-diephq commented on public/mix-manifest.json
> +}
dòng trắng cuối file

2017-12-08 01:43 UTC, at-diephq commented on resources/views/layouts/app.blade.php
> +
xóa dòng thừa này đi

2017-12-08 01:43 UTC, at-diephq commented on resources/views/tasks.blade.php
> +                    {!! Form::open(['route' => 'task.index', 'method' => 'POST', 'class' => 'form-horizontal']) !!}
> gợi ý : Trong laravelcolective thì Form::open nó hiểu mặc định method POST, nêú dùng POST thì em k cần khai báo method vẫn ok

2017-12-08 01:43 UTC, at-diephq commented on resources/views/layouts/app.blade.php
> +    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
dùng laravelcolective luôn em

2017-12-08 01:46 UTC, at-diephq commented
commented
Vì sao lại đưa những cái này lên (public/fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.svg) trong khi em đã có package.json để quản lý nó rồi

2017-12-08 01:58 UTC, lamngockhuong commented on resources/views/tasks.blade.php
> +                    {!! Form::open(['route' => 'task.index', 'method' => 'POST', 'class' => 'form-horizontal']) !!}
Dạ. em đã fix

2017-12-08 01:58 UTC, lamngockhuong commented on resources/views/layouts/app.blade.php
> +
Dạ rồi

2017-12-08 01:58 UTC, lamngockhuong commented on public/mix-manifest.json
> +}
(y)

2017-12-08 02:10 UTC, lamngockhuong commented on resources/views/layouts/app.blade.php
> +    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
Dạ em fix rồi

2017-12-08 02:10 UTC, lamngockhuong commented
ready

2017-12-08 02:16 UTC, at-diephq commented
commented
đã fix hết đâu (??)

2017-12-08 02:19 UTC, trangkarol commented on resources/views/tasks.blade.php
> +                    {{ csrf_field() }}
1. Đã dùng Form rồi thì không cần `{{ csrf_field() }}` nữa đâu em.
2. Em có biết dòng này để làm gì không?

2017-12-08 02:19 UTC, trangkarol commented on app/Http/Requests/TaskRequest.php
> +    }
Nghiên cứu để thêm function messages ở đây để I18n luôn em

2017-12-08 02:19 UTC, trangkarol commented
commented

2017-12-08 02:21 UTC, lamngockhuong commented on app/Http/Requests/TaskRequest.php
> +    }
Cái custom message e bỏ vào trong file validation.php để I18n rồi chị

2017-12-08 02:23 UTC, lamngockhuong commented on resources/views/tasks.blade.php
> +                    {{ csrf_field() }}
1. Chắc em kiểm tra xóa chưa hết.
2. crsf_token để chống attack Cross-Site Request Forgery (giả mạo người dungf)

2017-12-08 03:10 UTC, lamngockhuong commented
ready

2017-12-08 03:13 UTC, trangkarol commented
commented
Em thêm vào .gitinorge thì bỏ các file đó ở pull request này nhé

2017-12-08 03:22 UTC, lamngockhuong commented
ready

2017-12-08 03:25 UTC, trangkarol commented on public/mix-manifest.json
> +}
Em xem lại chỗ này e nhé

2017-12-08 03:42 UTC, trangkarol commented on public/mix-manifest.json
> +}
thiếu end line e ơi

2017-12-08 03:43 UTC, trangkarol commented
commented

2017-12-08 03:45 UTC, at-diephq commented
commented
(ok)

2017-12-08 03:46 UTC, trangkarol commented
merged
e tự merged đi nhé

2017-12-08 03:46 UTC, lamngockhuong commented
ready

2017-12-08 03:46 UTC, merged